import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";
import { useAuth } from "@/lib/auth";
import { atletaSchema, cpfDigitos, dataISO, dataTela, idade, mascaraCpf } from "@/lib/atleta-validation";
import { BotaoPrimario, CampoSelect, CampoTexto, Panel, Pill, SectionHeader } from "@/components/kit";

type Atleta = Tables<"atletas"> & { atletas_privado?: Tables<"atletas_privado"> | null; atleta_turmas?: { turma_id: string }[]; atleta_torneios?: { torneio_id: string }[] };
type Form = { nome: string; rg: string; cpf: string; nascimento: string; status: string; posicoes: string[]; categorias: string[]; turmas: string[]; torneios: string[]; possuiCamiseta: boolean; numero: string; medico: string };
const inicial: Form = { nome: "", rg: "", cpf: "", nascimento: "", status: "ativa", posicoes: [], categorias: [], turmas: [], torneios: [], possuiCamiseta: false, numero: "", medico: "pendente" };
function Multi({ titulo, valores, opcoes, mudar, gerenciar, somenteLeitura }: { titulo: string; valores: string[]; opcoes: { value: string; label: string }[]; mudar: (v: string[]) => void; gerenciar?: (() => void) | undefined; somenteLeitura?: boolean }) {
  return <div><div className="flex justify-between"><span className="label-mono">{titulo}</span>{gerenciar && <button type="button" onClick={gerenciar} className="text-[11px] text-primary">Adicionar opção</button>}</div><div className="mt-2 flex flex-wrap gap-2">{opcoes.filter(o => !somenteLeitura || valores.includes(o.value)).map(o => <label key={o.value} className={`rounded-[8px] border px-2.5 py-2 text-xs ${valores.includes(o.value) ? "border-primary bg-primary/15 text-primary" : "border-line bg-surface-2"}`}><input className="sr-only" type="checkbox" disabled={somenteLeitura} checked={valores.includes(o.value)} onChange={e => mudar(e.target.checked ? [...valores, o.value] : valores.filter(x => x !== o.value))} />{o.label}</label>)}</div>{!opcoes.length && <p className="text-xs text-muted-foreground mt-2">Nenhuma opção cadastrada.</p>}</div>;
}
export function AtletaFormulario({ atleta, turmas, torneios, opcoes, fechar }: { atleta?: Atleta; turmas: { id: string; nome: string }[]; torneios: { id: string; nome: string }[]; opcoes: { tipo: string; nome: string }[]; fechar: () => void }) {
  const { papel } = useAuth(); const gestor = papel === "gestora"; const qc = useQueryClient();
  const [form, setForm] = useState<Form>(() => atleta ? { nome: atleta.nome, rg: atleta.atletas_privado?.rg ?? "", cpf: mascaraCpf(atleta.atletas_privado?.cpf ?? ""), nascimento: dataTela(atleta.data_nascimento), status: atleta.status, posicoes: atleta.posicoes, categorias: atleta.categorias, turmas: atleta.atleta_turmas?.map(t => t.turma_id) ?? [], torneios: atleta.atleta_torneios?.map(t => t.torneio_id) ?? [], possuiCamiseta: atleta.possui_camiseta, numero: atleta.numero_camiseta?.toString() ?? "", medico: atleta.formulario_status } : inicial);
  const [erros, setErros] = useState<Record<string,string>>({}); const [foto, setFoto] = useState<File | null>(null); const [documento, setDocumento] = useState<File | null>(null); const [removerFoto, setRemoverFoto] = useState(false); const [removerDocumento, setRemoverDocumento] = useState(false);
  const [fotoUrl, setFotoUrl] = useState<string | null>(null);
  useEffect(() => { if (foto) { setFotoUrl(URL.createObjectURL(foto)); return; } if (!atleta?.foto_path || removerFoto) { setFotoUrl(null); return; } let ativo = true; supabase.storage.from("atletas-fotos").download(atleta.foto_path).then(({ data }) => { if (data && ativo) setFotoUrl(URL.createObjectURL(data)); }); return () => { ativo = false; }; }, [atleta?.foto_path, foto, removerFoto]);
  useEffect(() => () => { if (fotoUrl) URL.revokeObjectURL(fotoUrl); }, [fotoUrl]);
  const { data: historico = [] } = useQuery({ queryKey: ["historico-atleta", atleta?.id], enabled: !!atleta && gestor, queryFn: async () => { if (!atleta) return []; const { data } = await supabase.from("atleta_historico").select("*").eq("atleta_id", atleta.id).order("created_at", { ascending: false }).limit(50); return data ?? []; } });
  const mudar = <K extends keyof Form>(k: K, v: Form[K]) => { setForm(s => ({...s, [k]: v})); setErros(s => ({...s, [k]: ""})); };
  const escolher = (e: React.ChangeEvent<HTMLInputElement>, tipo: "foto" | "documento") => { const f = e.target.files?.[0]; if (!f) return; const ok = tipo === "foto" ? ["image/png","image/jpeg"].includes(f.type) && f.size <= 5*1024*1024 : f.type === "application/pdf" && f.size <= 10*1024*1024; if (!ok) { toast.error(tipo === "foto" ? "Escolha uma imagem PNG, JPG ou JPEG de até 5 MB." : "Escolha um arquivo PDF de até 10 MB."); e.target.value = ""; return; } if (tipo === "foto") { setFoto(f); setRemoverFoto(false); } else { setDocumento(f); setRemoverDocumento(false); } };
  const baixar = async (bucket: "atletas-fotos" | "atletas-documentos", path: string, nome: string) => { const { data, error } = await supabase.storage.from(bucket).download(path); if (error || !data) { toast.error("Não foi possível abrir o arquivo. Tente novamente."); return; } const url = URL.createObjectURL(data); const a = document.createElement("a"); a.href = url; a.download = nome; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const salvar = useMutation({ mutationFn: async () => {
    const result = atletaSchema.safeParse(form); if (!result.success) { const next: Record<string,string> = {}; result.error.issues.forEach(issue => { next[String(issue.path[0])] = issue.message; }); setErros(next); throw new Error("Confira os campos destacados antes de salvar."); }
     const nascimento = dataISO(form.nascimento);
     if (!nascimento) throw new Error("Confira a data de nascimento antes de salvar.");
     const payload = { nome: form.nome.trim(), data_nascimento: nascimento, status: form.status, posicoes: form.posicoes, categorias: form.categorias, possui_camiseta: form.possuiCamiseta, numero_camiseta: form.possuiCamiseta && form.numero ? Number(form.numero) : null, formulario_status: form.medico };
     // A função aceita NULL para novos cadastros; o tipo gerado marca o argumento como string.
     const { data: id, error: saveError } = await supabase.rpc("salvar_cadastro_atleta", { _id: (atleta?.id ?? null) as string, _dados: payload, _rg: form.rg.trim(), _cpf: cpfDigitos(form.cpf), _turmas: form.turmas, _torneios: form.torneios });
    if (saveError || !id) throw saveError ?? new Error("Falha ao salvar");
    if (foto || removerFoto) {
      if (foto) { const path = `${id}/${crypto.randomUUID()}.${foto.type === "image/png" ? "png" : "jpg"}`; const r = await supabase.storage.from("atletas-fotos").upload(path, foto); if (r.error) throw r.error; const u = await supabase.from("atletas").update({ foto_path: path, foto_nome: foto.name }).eq("id", id); if (u.error) throw u.error; }
      else { const u = await supabase.from("atletas").update({ foto_path: null, foto_nome: null }).eq("id", id); if (u.error) throw u.error; }
      if (atleta?.foto_path) await supabase.storage.from("atletas-fotos").remove([atleta.foto_path]);
    }
    if (documento || removerDocumento) {
      if (documento) { const path = `${id}/${crypto.randomUUID()}.pdf`; const r = await supabase.storage.from("atletas-documentos").upload(path, documento); if (r.error) throw r.error; const u = await supabase.from("atletas_privado").update({ documento_path: path, documento_nome: documento.name, documento_enviado_em: new Date().toISOString() }).eq("atleta_id", id); if (u.error) throw u.error; }
      else { const u = await supabase.from("atletas_privado").update({ documento_path: null, documento_nome: null, documento_enviado_em: null }).eq("atleta_id", id); if (u.error) throw u.error; }
      if (atleta?.atletas_privado?.documento_path) await supabase.storage.from("atletas-documentos").remove([atleta.atletas_privado.documento_path]);
    }
   }, onSuccess: () => { toast.success("Cadastro salvo com sucesso."); void qc.invalidateQueries({ queryKey: ["atletas"] }); fechar(); }, onError: (error: { code?: string; message?: string }) => { if (error.code === "23505") toast.error("Já existe uma atleta com este CPF ou número de camiseta ativo. Confira os dados."); else if (error.message?.startsWith("Confira")) toast.error(error.message); else toast.error("Não foi possível concluir o cadastro. Confira os dados e arquivos e tente novamente."); } });
  const cancelar = () => { if (!gestor || window.confirm("Deseja descartar as alterações e sair?")) fechar(); };
  const erro = (k: string) => erros[k] ? <p role="alert" className="text-xs text-danger mt-1">{erros[k]}</p> : null;
  const gestoraVinculos = (tipo: "posicao" | "categoria") => { const nome = window.prompt(`Nome da nova ${tipo}:`)?.trim(); if (!nome) return; if (nome.length > 40) { toast.error("Use no máximo 40 caracteres."); return; } void supabase.from("atleta_opcoes").insert({ tipo, nome }).then(({error}) => { if (error) toast.error("Não foi possível criar a opção. Confira se ela já existe."); else { toast.success("Opção cadastrada."); void qc.invalidateQueries({queryKey:["atletas-opcoes"]}); } }); };
  return <div className="space-y-4 rise">
    <div className="flex items-center justify-between"><div><p className="label-mono">Cadastro de atletas</p><h2 className="font-display text-[24px]">{atleta ? `Atleta #${atleta.numero}` : "Nova atleta"}</h2></div><button className="text-xs text-muted-foreground" onClick={cancelar}>Voltar</button></div>
    <Panel className="space-y-3"><SectionHeader titulo="01 / Dados pessoais" />
      <CampoTexto rotulo="ID da atleta" value={atleta?.numero ?? "Gerado ao salvar"} readOnly />
      {gestor ? <><CampoTexto rotulo="Nome completo *" maxLength={40} value={form.nome} onChange={e => mudar("nome",e.target.value)} />{erro("nome")}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><CampoTexto rotulo="RG *" maxLength={20} value={form.rg} onChange={e => mudar("rg",e.target.value)} />{erro("rg")}</div><div><CampoTexto rotulo="CPF *" inputMode="numeric" value={form.cpf} onChange={e => mudar("cpf", mascaraCpf(e.target.value))} placeholder="000.000.000-00" />{erro("cpf")}</div></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><CampoTexto rotulo="Data de nascimento * (DD/MM/AAAA)" placeholder="DD/MM/AAAA" value={form.nascimento} onChange={e => mudar("nascimento",e.target.value)} />{erro("nascimento")}<input type="date" aria-label="Selecionar data no calendário" max={new Date().toISOString().slice(0,10)} className="mt-2 text-xs bg-surface-2 text-foreground rounded p-2" onChange={e => mudar("nascimento",dataTela(e.target.value))} /></div><CampoTexto rotulo="Idade (calculada)" readOnly value={idade(dataISO(form.nascimento)) ?? "—"} /></div>
      <CampoSelect rotulo="Status *" value={form.status} onChange={e => mudar("status",e.target.value)}><option value="ativa">Ativa</option><option value="inativa">Inativa</option></CampoSelect></> : <><p className="text-sm">{atleta?.nome}</p><p className="text-xs text-muted-foreground">Idade: {idade(atleta?.data_nascimento ?? null) ?? "—"} · {atleta?.status}</p></>}
       <div><p className="label-mono">Foto da atleta {!(atleta?.foto_path || foto) && <span title="Foto pendente" className="text-warning">!</span>}</p>{fotoUrl && <img src={fotoUrl} alt="Prévia da foto" className="size-24 object-cover rounded-[8px] mt-2" />}{gestor && <input type="file" accept="image/png,image/jpeg" aria-label="Enviar foto" className="block mt-2 text-xs max-w-full" onChange={e => escolher(e,"foto")} />}{atleta?.foto_path && !removerFoto && <div className="flex gap-3 mt-2"><button className="text-xs text-primary" onClick={() => { if (atleta.foto_path) void baixar("atletas-fotos",atleta.foto_path,atleta.foto_nome || "foto.jpg"); }}>Baixar foto</button>{gestor && <button className="text-xs text-danger" onClick={() => { if(window.confirm("Remover a foto desta atleta?")){setRemoverFoto(true);setFoto(null);} }}>Remover foto</button>}</div>}</div>
    </Panel>
    <Panel className="space-y-4"><SectionHeader titulo="02 / Informações esportivas" />
       <Multi titulo="Posições *" valores={form.posicoes} opcoes={opcoes.filter(o => o.tipo === "posicao").map(o => ({value:o.nome,label:o.nome}))} mudar={v => mudar("posicoes",v)} gerenciar={gestor ? () => gestoraVinculos("posicao") : undefined} somenteLeitura={!gestor} />{erro("posicoes")}
       <Multi titulo="Categorias *" valores={form.categorias} opcoes={opcoes.filter(o => o.tipo === "categoria").map(o => ({value:o.nome,label:o.nome}))} mudar={v => mudar("categorias",v)} gerenciar={gestor ? () => gestoraVinculos("categoria") : undefined} somenteLeitura={!gestor} />{erro("categorias")}
       <Multi titulo="Turmas (opcional)" valores={form.turmas} opcoes={turmas.map(t => ({value:t.id,label:t.nome}))} mudar={v => mudar("turmas",v)} somenteLeitura={!gestor} />
       <Multi titulo="Torneios (opcional)" valores={form.torneios} opcoes={torneios.map(t => ({value:t.id,label:t.nome}))} mudar={v => mudar("torneios",v)} somenteLeitura={!gestor} />
      {gestor ? <><CampoSelect rotulo="Possui camiseta do time? *" value={form.possuiCamiseta ? "sim" : "nao"} onChange={e => { mudar("possuiCamiseta",e.target.value === "sim"); if(e.target.value === "nao") mudar("numero",""); }}><option value="nao">Não</option><option value="sim">Sim</option></CampoSelect>{form.possuiCamiseta && <><CampoTexto rotulo="Número da camiseta" type="number" min="0" max="999" value={form.numero} onChange={e => mudar("numero",e.target.value)} />{erro("numero")}</>}</> : <p className="text-xs">Camiseta: {form.possuiCamiseta ? `Sim${form.numero ? ` · nº ${form.numero}` : ""}` : "Não"}</p>}
    </Panel>
     <Panel className="space-y-3"><SectionHeader titulo="03 / Formulário médico" /><Pill tom={form.medico === "preenchido" ? "sucesso" : "alerta"}>{form.medico === "preenchido" ? "Preenchido" : form.medico === "pendente" ? "Pendente" : "Atualização necessária"}</Pill>{form.medico !== "preenchido" && <span className="ml-2 text-warning" title="Formulário médico pendente ou precisa de atualização" aria-label="Formulário médico pendente ou precisa de atualização">!</span>}
      {gestor && <CampoSelect rotulo="Situação do formulário" value={form.medico} onChange={e => mudar("medico",e.target.value)}><option value="pendente">Pendente</option><option value="preenchido">Preenchido</option><option value="atualizacao_necessaria">Atualização necessária</option></CampoSelect>}
      {atleta?.formulario_preenchido_em && <p className="text-xs text-muted-foreground">Preenchido em {new Date(atleta.formulario_preenchido_em).toLocaleDateString("pt-BR")}</p>}{atleta?.formulario_atualizado_em && <p className="text-xs text-muted-foreground">Última atualização em {new Date(atleta.formulario_atualizado_em).toLocaleDateString("pt-BR")}</p>}
      <p className="text-xs text-muted-foreground">Confira as respostas diretamente no Google Forms. A sincronização de respostas ainda depende de autorização e configuração da conta do formulário.</p>
    </Panel>
     {gestor && <Panel className="space-y-3"><SectionHeader titulo="04 / Documentos" />{atleta?.atletas_privado?.documento_nome && !removerDocumento ? <><p className="text-xs">{atleta.atletas_privado.documento_nome} · Enviado em {atleta.atletas_privado.documento_enviado_em ? new Date(atleta.atletas_privado.documento_enviado_em).toLocaleDateString("pt-BR") : "—"}</p><div className="flex gap-3"><button className="text-xs text-primary" onClick={() => { const doc = atleta.atletas_privado; if (doc?.documento_path) void baixar("atletas-documentos",doc.documento_path,doc.documento_nome || "documento.pdf"); }}>Abrir / baixar PDF</button><button className="text-xs text-danger" onClick={() => { if (window.confirm("Deseja remover este documento?")) { setRemoverDocumento(true); setDocumento(null); } }}>Remover</button></div></> : <p className="text-xs text-warning" title="Documento de identificação pendente">! Documento ainda não anexado</p>}<label className="block text-xs">{atleta?.atletas_privado?.documento_nome ? "Substituir documento (PDF)" : "Anexar documento (PDF)"}<input type="file" accept="application/pdf" className="block mt-2 max-w-full" onChange={e => escolher(e,"documento")} /></label></Panel>}
    {gestor && atleta && <Panel><SectionHeader titulo="05 / Histórico" />{historico.length ? <div className="space-y-2 max-h-56 overflow-y-auto">{historico.map(h => <div key={h.id} className="border-b border-line py-2 text-xs"><span className="text-muted-foreground">{new Date(h.created_at).toLocaleString("pt-BR")} · {h.responsavel_id?.slice(0,8) ?? "Sistema"}</span><p>{h.campo.replaceAll("_"," ")}: {h.anterior || "—"} → {h.novo || "—"}</p></div>)}</div> : <p className="text-xs text-muted-foreground">Ainda não há alterações registradas.</p>}</Panel>}
    {gestor && <div className="flex gap-2"><BotaoPrimario disabled={salvar.isPending} onClick={() => salvar.mutate()}>{salvar.isPending ? "Salvando..." : "Salvar"}</BotaoPrimario><button className="w-full rounded-[8px] border border-line text-sm" onClick={cancelar}>Cancelar</button></div>}
  </div>;
}
