/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtletasRouteImport } from './routes/atletas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as TorneiosRouteImport } from './routes/torneios'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as UniformesRouteImport } from './routes/uniformes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasRoute = AtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosRoute = TorneiosRouteImport.update({
  id: '/torneios',
  path: '/torneios',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformesRoute = UniformesRouteImport.update({
  id: '/uniformes',
  path: '/uniformes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/torneios': typeof TorneiosRoute
  '/turmas': typeof TurmasRoute
  '/uniformes': typeof UniformesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/torneios': typeof TorneiosRoute
  '/turmas': typeof TurmasRoute
  '/uniformes': typeof UniformesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atletas': typeof AtletasRoute
  '/auth': typeof AuthRoute
  '/financeiro': typeof FinanceiroRoute
  '/materiais': typeof MateriaisRoute
  '/perfil': typeof PerfilRoute
  '/torneios': typeof TorneiosRoute
  '/turmas': typeof TurmasRoute
  '/uniformes': typeof UniformesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atletas'
    | '/auth'
    | '/financeiro'
    | '/materiais'
    | '/perfil'
    | '/torneios'
    | '/turmas'
    | '/uniformes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atletas'
    | '/auth'
    | '/financeiro'
    | '/materiais'
    | '/perfil'
    | '/torneios'
    | '/turmas'
    | '/uniformes'
  id:
    | '__root__'
    | '/'
    | '/atletas'
    | '/auth'
    | '/financeiro'
    | '/materiais'
    | '/perfil'
    | '/torneios'
    | '/turmas'
    | '/uniformes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtletasRoute: typeof AtletasRoute
  AuthRoute: typeof AuthRoute
  FinanceiroRoute: typeof FinanceiroRoute
  MateriaisRoute: typeof MateriaisRoute
  PerfilRoute: typeof PerfilRoute
  TorneiosRoute: typeof TorneiosRoute
  TurmasRoute: typeof TurmasRoute
  UniformesRoute: typeof UniformesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas': {
      id: '/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AtletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios': {
      id: '/torneios'
      path: '/torneios'
      fullPath: '/torneios'
      preLoaderRoute: typeof TorneiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniformes': {
      id: '/uniformes'
      path: '/uniformes'
      fullPath: '/uniformes'
      preLoaderRoute: typeof UniformesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtletasRoute: AtletasRoute,
  AuthRoute: AuthRoute,
  FinanceiroRoute: FinanceiroRoute,
  MateriaisRoute: MateriaisRoute,
  PerfilRoute: PerfilRoute,
  TorneiosRoute: TorneiosRoute,
  TurmasRoute: TurmasRoute,
  UniformesRoute: UniformesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
